version: '3'

# service description
services:

  # watchtower service
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    labels:
      # enbale watchtower updates
      - "com.centurylinklabs.watchtower.enable=true"